import type { Metadata } from "next";
import "@/styles/globals.css";
import { Toaster } from "@/components/ui/sonner";
import { AuthModal } from "./(auth)/_components/auth-modal";
import Provider from "./_components/provider";
import localFont from "next/font/local";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: {
    default: "Next Dashboard | Zulmy Azhary",
    template: "Next Dashboard | %s",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <body
        className={`$${geistSans.variable} ${geistMono.variable} flex flex-col min-h-screen`}
      >
        <Provider>
          <main className="flex-grow">{children}</main>
          <AuthModal />
          <Toaster position="top-right" richColors theme="light" />
        </Provider>
      </body>
    </html>
  );
}
