import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import { Toaster } from "@/components/ui/sonner";
import { AuthModal } from "./(auth)/_components/auth-modal";
import Provider from "./_components/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    default: "Next Dashboard | Zulmy Azhary",
    template: "Next Dashboard | %s",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col min-h-screen`}>
        <Provider>
          <main className="flex-grow">{children}</main>
          <AuthModal />
          <Toaster position="top-right" richColors theme="light" />
        </Provider>
      </body>
    </html>
  );
}
